# Generated by Django 6.0.3 on 2026-03-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='baslik',
            field=models.CharField(max_length=300),
        ),
    ]
