[
  {
    "ad": "Römerberg",
    "kategori": "tarihi_yer",
    "stadt": "frankfurt",
    "adres": "Römerberg, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.110277,8.682222",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/e/ee/R%C3%B6merberg_Frankfurt_abends.jpg",
    "website": "https://www.frankfurt.de/",
    "aciklama": "Frankfurt'un tarihi kalbi olan, orta çağdan kalma yarı ahşap evleri ve meşhur Adalet Çeşmesi'ni barındıran ikonik meydan.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/R%C3%B6merberg_(Frankfurt_am_Main)",
    "sira": 1
  },
  {
    "ad": "Frankfurt Katedrali",
    "kategori": "dini_yapi",
    "stadt": "frankfurt",
    "adres": "Domplatz 1, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.110556,8.685278",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Frankfurt_am_Main%2C_Kaiserdom_--_2015_--_6727.jpg",
    "website": "https://www.dom-frankfurt.de",
    "aciklama": "Kutsal Roma İmparatorlarının taç giyme törenlerine ev sahipliği yapmış, 95 metre yüksekliğinde kuleye sahip devasa gotik katedral.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Frankfurt_Katedrali",
    "sira": 2
  },
  {
    "ad": "Goethe-Haus",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Großer Hirschgraben 23, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.111111,8.6775",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/8/87/Goethe_House_Frankfurt.jpg",
    "website": "https://frankfurter-goethe-haus.de",
    "aciklama": "Ünlü Alman yazar Johann Wolfgang von Goethe'nin doğduğu ve gençlik yıllarını geçirdiği, aslına uygun restore edilmiş tarihi ev.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Goethe_Evi",
    "sira": 3
  },
  {
    "ad": "Städel Museum",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Schaumainkai 63, 60596 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.103333,8.673889",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/3/36/St%C3%A4del_Museum%2C_August_2022.jpg",
    "website": "https://www.staedelmuseum.de",
    "aciklama": "700 yıllık Avrupa sanat tarihini kapsayan, Almanya'nın en önemli ve prestijli sanat müzelerinden biri.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/St%C3%A4del",
    "sira": 4
  },
  {
    "ad": "Alte Oper",
    "kategori": "kultur",
    "stadt": "frankfurt",
    "adres": "Opernplatz 1, 60313 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.115833,8.671944",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/8/82/Alte_Oper_Frankfurt_Winter_2008.jpg",
    "website": "https://www.alteoper.de",
    "aciklama": "1880 yılında inşa edilen ve 2. Dünya Savaşı sonrası konser salonu olarak yeniden açılan, Neo-Rönesans mimarisine sahip ikonik eski opera binası.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Alte_Oper",
    "sira": 5
  },
  {
    "ad": "Eiserner Steg",
    "kategori": "gezi",
    "stadt": "frankfurt",
    "adres": "Mainkai, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.108056,8.682222",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Eiserner_Steg_in_Frankfurt_am_Main.jpg",
    "website": "https://frankfurt.de",
    "aciklama": "1869 yılında Main Nehri üzerine inşa edilen, Frankfurt'un iki yakasını birbirine bağlayan ve eşsiz bir şehir silüeti sunan tarihi demir yaya köprüsü.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Eiserner_Steg_(Frankfurt_am_Main)",
    "sira": 6
  },
  {
    "ad": "Historisches Museum Frankfurt",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Saalhof 1, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.109722,8.6825",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Historisches_Museum_Frankfurt.jpg",
    "website": "https://www.historisches-museum-frankfurt.de",
    "aciklama": "Frankfurt'un Orta Çağ'dan günümüze uzanan zengin şehir tarihini kapsamlı koleksiyonlar ve maketlerle anlatan Avrupa'nın en büyük şehir müzelerinden biri.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Historisches_Museum_Frankfurt",
    "sira": 7
  },
  {
    "ad": "MMK Museum für Moderne Kunst",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Domstraße 10, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.111797,8.684264",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/5/52/Museum_f%C3%BCr_Moderne_Kunst%2C_main_entrance%2C_in_2009.jpg",
    "website": "https://www.mmk.art",
    "aciklama": "Hans Hollein'in tasarladığı üçgen mimarisiyle ünlü, 1960'lardan günümüze dünyanın en önemli çağdaş sanat koleksiyonlarına ev sahipliği yapan müze.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Museum_f%C3%BCr_Moderne_Kunst",
    "sira": 8
  },
  {
    "ad": "Senckenberg Naturmuseum",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Senckenberganlage 25, 60325 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.1175,8.651667",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/9/91/Naturmuseum_Senckenberg.jpg",
    "website": "https://museumfrankfurt.senckenberg.de",
    "aciklama": "Avrupa'nın en büyük dinazor ve paleontoloji koleksiyonlarından birini barındıran, evrim ve biyolojik çeşitlilik odaklı doğa tarihi müzesi.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Senckenberg_Naturmuseum",
    "sira": 9
  },
  {
    "ad": "Palmengarten",
    "kategori": "doga",
    "stadt": "frankfurt",
    "adres": "Siesmayerstraße 63, 60323 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.123611,8.655556",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Palmengarten_Frankfurt.jpg",
    "website": "https://www.palmengarten.de",
    "aciklama": "1871'de açılan, dünyanın dört bir yanından gelen bitki türlerinin devasa seralarda sergilendiği, 22 hektarlık büyüleyici botanik bahçesi.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Palmengarten_Frankfurt",
    "sira": 10
  },
  {
    "ad": "Main Tower",
    "kategori": "gezi",
    "stadt": "frankfurt",
    "adres": "Neue Mainzer Straße 52-58, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.112222,8.671944",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/1/18/Maintower_Frankfurt.jpg",
    "website": "https://www.maintower.de",
    "aciklama": "Frankfurt'un gökdelenler silüetini 200 metre yükseklikten panoramik olarak izleyebileceğiniz, halka açık seyir terasına sahip tek gökdeleni.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Main_Tower",
    "sira": 11
  },
  {
    "ad": "Paulskirche",
    "kategori": "tarihi_yer",
    "stadt": "frankfurt",
    "adres": "Paulsplatz 11, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.111111,8.680833",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Frankfurt_Paulskirche_um_1900.jpg",
    "website": "https://frankfurt.de",
    "aciklama": "1848 yılında ilk demokratik Alman Ulusal Meclisi'nin toplandığı, Alman demokrasisinin beşiği sayılan tarihi kilise ve anıt yapı.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Paulskirche_(Frankfurt_am_Main)",
    "sira": 12
  },
  {
    "ad": "Kleinmarkthalle",
    "kategori": "lezzet",
    "stadt": "frankfurt",
    "adres": "Hasengasse 5-7, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.112778,8.683056",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Kleinmarkthalle_Frankfurt.jpg",
    "website": "https://www.kleinmarkthalle.de",
    "aciklama": "Yerel Frankfurt sosislerinden uluslararası gurme ürünlere kadar 60'tan fazla pazar tezgahının bulunduğu canlı ve tarihi kapalı pazar alanı.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Kleinmarkthalle_Frankfurt",
    "sira": 13
  },
  {
    "ad": "Schirn Kunsthalle",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Römerberg, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.110278,8.683611",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Schirn_Kunsthalle_Frankfurt.jpg",
    "website": "https://www.schirn.de",
    "aciklama": "Kendi koleksiyonu olmamasına rağmen, modern ve çağdaş sanatın en iddialı ve provokatif geçici sergilerine ev sahipliği yapan saygın sanat galerisi.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Schirn_Kunsthalle_Frankfurt",
    "sira": 14
  },
  {
    "ad": "Jüdisches Museum Frankfurt",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Bertha-Pappenheim-Platz 1, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.1075,8.673889",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/3/37/J%C3%BCdisches_Museum_Frankfurt.jpg",
    "website": "https://www.juedischesmuseum.de",
    "aciklama": "Aydınlanma çağından günümüze Frankfurt'un köklü Yahudi cemaatinin tarihini, kültürünü ve Holokost anılarını anlatan etkileyici müze.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/J%C3%BCdisches_Museum_Frankfurt",
    "sira": 15
  },
  {
    "ad": "Liebieghaus",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Schaumainkai 71, 60596 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.101944,8.671667",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/6/69/Liebieghaus_in_2005.jpg",
    "website": "https://www.liebieghaus.de",
    "aciklama": "Antik Mısır'dan Neoklasik döneme kadar 5000 yıllık heykeltıraşlık tarihini büyüleyici bir 19. yüzyıl villasında sergileyen heykel müzesi.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Liebieghaus",
    "sira": 16
  },
  {
    "ad": "Museum Angewandte Kunst",
    "kategori": "muze",
    "stadt": "frankfurt",
    "adres": "Schaumainkai 17, 60594 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.106389,8.681389",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/d/df/Museum_Angewandte_Kunst.jpg",
    "website": "https://www.museumangewandtekunst.de",
    "aciklama": "Richard Meier tarafından tasarlanan binasında tasarım, moda ve el sanatlarının çağdaş ve estetik normlarını ziyaretçilerle buluşturan sanat müzesi.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Museum_Angewandte_Kunst_(Frankfurt_am_Main)",
    "sira": 17
  },
  {
    "ad": "Zoo Frankfurt",
    "kategori": "doga",
    "stadt": "frankfurt",
    "adres": "Bernhard-Grzimek-Allee 1, 60316 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.115833,8.701944",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Zoo_Frankfurt.jpg",
    "website": "https://www.zoo-frankfurt.de",
    "aciklama": "1858 yılında kurulan, Almanya'nın en eski ikinci hayvanat bahçesi olup, 450'den fazla egzotik hayvan türüne ev sahipliği yapar.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/Zoo_Frankfurt",
    "sira": 18
  },
  {
    "ad": "Römer",
    "kategori": "tarihi_yer",
    "stadt": "frankfurt",
    "adres": "Römerberg 23, 60311 Frankfurt am Main",
    "maps_url": "https://maps.google.com/?q=50.110278,8.682222",
    "kapak_resmi": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Frankfurter_R%C3%B6mer_2019.jpg",
    "website": "https://frankfurt.de",
    "aciklama": "15. yüzyıldan beri Frankfurt Belediye Binası olarak hizmet veren, kendine has üç basamaklı alınlık cephesiyle şehrin en ikonik siyasi sembolü.",
    "wikipedia_url": "https://tr.wikipedia.org/wiki/R%C3%B6mer_(Frankfurt_am_Main)",
    "sira": 19
  }
]