# Generated by Django 5.2.9 on 2026-03-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oneri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('oneri', 'Öneri'), ('hata', 'Hata Bildirimi'), ('icerik', 'İçerik Talebi'), ('diger', 'Diğer')], default='oneri', max_length=20, verbose_name='Tür')),
                ('ad', models.CharField(blank=True, max_length=100, verbose_name='Ad Soyad')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'Öneri',
                'verbose_name_plural': 'Öneriler',
                'ordering': ['-olusturulma'],
            },
        ),
    ]
