# Generated by Django 6.0.3 on 2026-03-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnemliLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('kategori', models.CharField(choices=[('resmi', 'Resmi Kurum'), ('ilan', 'İlan Platformu'), ('is', 'İş & Kariyer'), ('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('ulasim', 'Ulaşım'), ('haber', 'Haber & Bilgi'), ('diger', 'Diğer')], max_length=20)),
                ('aciklama', models.TextField(blank=True)),
                ('randevu_url', models.URLField(blank=True, help_text='Varsa randevu/iletişim linki')),
                ('aktif', models.BooleanField(default=True)),
                ('sira', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Önemli Link',
                'verbose_name_plural': 'Önemli Linkler',
                'ordering': ['kategori', 'sira', 'ad'],
            },
        ),
    ]
