# Generated by Django 6.0.3 on 2026-03-23 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konusma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('taraf1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konusmalar_taraf1', to=settings.AUTH_USER_MODEL)),
                ('taraf2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konusmalar_taraf2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konuşma',
                'verbose_name_plural': 'Konuşmalar',
                'unique_together': {('taraf1', 'taraf2')},
            },
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('okundu', models.BooleanField(default=False)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('konusma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='mesajlar.konusma')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['olusturulma'],
            },
        ),
    ]
