# Generated by Django 5.2.9 on 2026-03-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_eyalet_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konu',
            name='scope',
            field=models.CharField(choices=[('stadt', 'Şehre Özel'), ('eyalet', 'RLP Geneli'), ('global', 'Genel')], default='eyalet', max_length=10, verbose_name='Kapsam'),
        ),
    ]
