# Generated by Django 5.2.9 on 2026-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_eyalet_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogyazisi',
            name='scope',
            field=models.CharField(choices=[('stadt', 'Şehre Özel'), ('eyalet', 'Eyalet Geneli'), ('genel', 'Almanya Geneli')], default='eyalet', max_length=10, verbose_name='Kapsam'),
        ),
    ]
