# Generated by Django 5.2.9 on 2026-03-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0023_seed_mannheim_kaynaklar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BultenAbone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Bülten Abonesi',
                'verbose_name_plural': 'Bülten Aboneleri',
                'ordering': ['-kayit_tarihi'],
            },
        ),
    ]
