# Generated by Django 5.2.9 on 2026-03-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0027_seed_koeln_kaynaklar'),
        ('stadt', '0018_seed_koeln_stadt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=300, verbose_name='Başlık')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='belgeler/pdf/', verbose_name='Dosya (PDF/DOCX)')),
                ('harici_link', models.URLField(blank=True, help_text='Dosya bizde değilse resmi kurumun linki', null=True, verbose_name='Harici Link')),
                ('kategori', models.CharField(choices=[('aile', 'Aile & Çocuk'), ('konut', 'Konut & Kira'), ('vize', 'Vize & Oturum'), ('is', 'İş & Eğitim'), ('genel', 'Genel')], default='genel', max_length=10, verbose_name='Kategori')),
                ('ozet', models.CharField(blank=True, max_length=300, verbose_name='Kısa Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('yayinda', models.BooleanField(default=True, verbose_name='Yayında')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('stadt', models.ForeignKey(blank=True, help_text='Boşsa Federal (Tüm Almanya)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadt.stadt', verbose_name='Şehir')),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['kategori', 'sira', 'baslik'],
            },
        ),
    ]
