# Generated by Django 5.2.9 on 2026-04-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0035_merge_20260402_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaynak',
            name='randevu_url',
            field=models.URLField(blank=True, help_text='Varsa randevu/iletişim linki', verbose_name='Randevu Linki'),
        ),
    ]
