# Generated by Django 5.2.9 on 2026-04-10 18:29

from django.db import migrations

# OnemliLink kategori → Kaynak kategori eşleşmesi
KATEGORI_MAP = {
    'resmi':  'resmi',
    'ilan':   'ilan',
    'is':     'is',
    'egitim': 'egitim',
    'saglik': 'saglik',
    'ulasim': 'ulasim',
    'haber':  'haber',
    'diger':  'diger',
}

# OnemliLink scope → Kaynak scope eşleşmesi
SCOPE_MAP = {
    'stadt':  'stadt',
    'eyalet': 'eyalet',
}


def onemlilink_to_kaynak(apps, schema_editor):
    OnemliLink = apps.get_model('linkler', 'OnemliLink')
    Kaynak = apps.get_model('rehber', 'Kaynak')

    for link in OnemliLink.objects.select_related('eyalet', 'stadt').all():
        # Zaten var mı kontrol et (url'ye göre)
        if link.url and Kaynak.objects.filter(url=link.url).exists():
            continue

        Kaynak.objects.create(
            eyalet=link.eyalet,
            stadt=link.stadt,
            scope=SCOPE_MAP.get(link.scope, 'eyalet'),
            baslik=link.ad,
            tip='link',
            url=link.url,
            kategori=KATEGORI_MAP.get(link.kategori, 'diger'),
            ozet=link.aciklama or '',
            randevu_url=link.randevu_url or '',
            sira=link.sira,
            yayinda=link.aktif,
        )


def reverse_migration(apps, schema_editor):
    # Geri alınamaz — data migration tek yönlü
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0036_kaynak_randevu_url'),
        ('linkler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(onemlilink_to_kaynak, reverse_migration),
    ]
