# Generated by Django 6.0.3 on 2026-03-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('resmi_kurum', 'Resmi Kurum'), ('alisveris', 'Alışveriş Merkezi'), ('turk_market', 'Türk Marketi'), ('ibadet', 'Cami / İbadethane'), ('tuv', 'TÜV / GTÜ İstasyonu'), ('saglik', 'Sağlık'), ('egitim', 'Eğitim'), ('gezi', 'Gezi & Kültür'), ('yeme_icme', 'Yeme & İçme'), ('diger', 'Diğer')], max_length=20)),
                ('adres', models.TextField()),
                ('sehir', models.CharField(default='Mainz', max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('maps_url', models.URLField(blank=True, help_text='Google Maps linki')),
                ('aciklama', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Yer',
                'verbose_name_plural': 'Yerler',
                'ordering': ['kategori', 'ad'],
            },
        ),
    ]
