# Generated by Django 5.2.9 on 2026-03-21 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadt', '0001_initial'),
        ('yerler', '0002_kapak_icerik_wikipedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='yer',
            name='scope',
            field=models.CharField(choices=[('stadt', 'Şehre Özel'), ('eyalet', 'RLP Geneli')], default='stadt', max_length=10, verbose_name='Kapsam'),
        ),
        migrations.AddField(
            model_name='yer',
            name='stadt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadt.stadt', verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='yer',
            name='sehir',
            field=models.CharField(default='Mainz', help_text='Eski alan - migration sonrası kullanılmayacak', max_length=100),
        ),
    ]
