# Generated by Django 5.2.9 on 2026-03-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0005_reklampaketi_yer_calisma_saati_yer_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yer',
            name='kapak_foto',
            field=models.ImageField(blank=True, null=True, upload_to='yerler/kapak/', verbose_name='Kapak Fotoğrafı (yükle)'),
        ),
        migrations.AddField(
            model_name='yerfoto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='yerler/fotolar/', verbose_name='Fotoğraf (yükle)'),
        ),
        migrations.AlterField(
            model_name='yer',
            name='kapak_resmi',
            field=models.URLField(blank=True, verbose_name='Kapak Resmi URL (harici)'),
        ),
        migrations.AlterField(
            model_name='yerfoto',
            name='url',
            field=models.URLField(blank=True, verbose_name='Fotoğraf URL (harici)'),
        ),
    ]
