# Generated by Django 5.2.9 on 2026-03-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0006_yer_kapak_foto_yerfoto_foto_alter_yer_kapak_resmi_and_more'),
    ]

    operations = [
        # aciklama daha önce uygulanmış olabilir — mevcut değilse ekle
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    lambda apps, se: None if 'aciklama' in [
                        c.name for c in se.connection.introspection.get_table_description(
                            se.connection.cursor(), 'yerler_reklampaketi'
                        )
                    ] else se.execute(
                        "ALTER TABLE yerler_reklampaketi ADD COLUMN aciklama varchar(200) NOT NULL DEFAULT ''"
                    ),
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='reklampaketi',
                    name='aciklama',
                    field=models.CharField(blank=True, max_length=200, verbose_name='Kısa Açıklama'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='yer',
            name='tur',
            field=models.CharField(choices=[('yer', 'Önemli Yer'), ('isletme', 'İşletme')], default='yer', max_length=10, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='reklampaketi',
            name='iletisim_notu',
            field=models.TextField(blank=True, verbose_name='İletişim Notu'),
        ),
        migrations.AlterField(
            model_name='reklampaketi',
            name='ozellikler',
            field=models.TextField(help_text='Her satır bir özellik', verbose_name='Özellikler'),
        ),
        migrations.AlterField(
            model_name='reklampaketi',
            name='renk',
            field=models.CharField(default='primary', max_length=30, verbose_name='Bootstrap Renk'),
        ),
        migrations.AlterField(
            model_name='reklampaketi',
            name='sure_etiketi',
            field=models.CharField(default='/ ay', max_length=50, verbose_name='Süre Etiketi'),
        ),
        migrations.AlterField(
            model_name='reklampaketi',
            name='vurgulu',
            field=models.BooleanField(default=False, verbose_name='Vurgulu Göster'),
        ),
        migrations.AlterField(
            model_name='yer',
            name='calisma_saati',
            field=models.CharField(blank=True, max_length=200, verbose_name='Çalışma Saatleri'),
        ),
        migrations.AlterField(
            model_name='yer',
            name='kategori',
            field=models.CharField(choices=[('resmi_kurum', 'Resmi Kurum'), ('ibadet', 'Cami / İbadethane'), ('tuv', 'TÜV / GTÜ İstasyonu'), ('saglik', 'Sağlık'), ('egitim', 'Eğitim'), ('gezi', 'Gezi & Kültür'), ('alisveris', 'Alışveriş Merkezi'), ('turk_market', 'Türk Marketi'), ('yeme_icme', 'Yeme & İçme')], max_length=20),
        ),
        migrations.AlterField(
            model_name='yer',
            name='paket',
            field=models.CharField(choices=[('ucretsiz', 'Ücretsiz'), ('temel', 'Temel'), ('plus', 'Plus'), ('pro', 'Pro')], default='ucretsiz', max_length=10, verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='yer',
            name='sehir',
            field=models.CharField(default='Mainz', help_text='Eski alan', max_length=100),
        ),
        migrations.AlterField(
            model_name='yer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
