# Generated by Django 5.2.9 on 2026-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0006_yer_kapak_foto_yerfoto_foto_alter_yer_kapak_resmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklampaketi',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Paket kartında başlığın altında gösterilir', max_length=200, verbose_name='Kısa Açıklama'),
        ),
    ]
