# Generated by Django 5.2.9 on 2026-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0007_reklampaketi_aciklama_yer_tur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YerKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Slug (kod)')),
                ('ad', models.CharField(max_length=100, verbose_name='Görünen Ad')),
                ('tur', models.CharField(choices=[('yer', 'Önemli Yer'), ('isletme', 'İşletme')], default='isletme', max_length=10, verbose_name='Tür')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['tur', 'sira', 'ad'],
            },
        ),
        migrations.AlterField(
            model_name='yer',
            name='kategori',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
