# Generated by Django 5.2.9 on 2026-03-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0007_reklampaketi_aciklama'),
        ('yerler', '0008_yerkategori_model'),
    ]

    operations = [
    ]
