# Generated by Django 5.2.9 on 2026-04-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0031_merge_20260402_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yer',
            name='kapak_resmi',
            field=models.URLField(blank=True, max_length=500, verbose_name='Kapak Resmi URL (harici)'),
        ),
        migrations.AlterField(
            model_name='yer',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Google Maps linki', max_length=500),
        ),
    ]
