# Generated by Django 6.0.3 on 2026-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0033_seed_frankfurt_yerler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yer',
            name='ad',
            field=models.CharField(max_length=200, verbose_name='Yer Adı'),
        ),
    ]
