# Generated by Django 5.2.9 on 2026-05-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0044_seed_hannover_yerler'),
        ('yerler', '0045_seed_erfurt_yerler'),
    ]

    operations = [
    ]
