# Generated by Django 5.2.9 on 2026-03-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şehir Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('typ', models.CharField(choices=[('kreisfrei', 'Kreisfreie Stadt'), ('landkreis', 'Landkreis')], default='kreisfrei', max_length=20, verbose_name='Tür')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Enlem')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Boylam')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Nüfus')),
                ('auslaenderbehorde_url', models.URLField(blank=True, verbose_name='Ausländerbehörde URL')),
                ('termin_url', models.URLField(blank=True, verbose_name='Randevu URL')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktiv', models.BooleanField(default=False, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
                'ordering': ['name'],
            },
        ),
    ]
