# Generated by Django 5.2.9 on 2026-03-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadt', '0013_fix_mainz_urls_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadt',
            name='rss_duyuru_url',
            field=models.URLField(blank=True, verbose_name='Belediye RSS / Haber URL'),
        ),
    ]
