# Generated by Django 5.2.9 on 2026-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadt', '0035_fix_bochum_kdu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadt',
            name='kapak_resmi_url',
            field=models.URLField(blank=True, verbose_name='Kapak Fotoğrafı URL'),
        ),
    ]
