# Generated by Django 5.2.9 on 2026-05-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadt', '0045_erfurt_aktiv'),
        ('stadt', '0045_eyalet_nrw_artik_sil'),
    ]

    operations = [
    ]
